[build-system]
requires = ["setuptools", "wheel", "cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "perfect_cmaps"
version = "1.4.0"
description = "Create amazing perceptually uniform colormaps with ease!"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.6"
authors = [
    {name = "Mattias Ulmestrand", email = "m.ulmestrand@gmail.com"}
]
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "colour-science",
    "scipy",
    "opencv-python-headless",
    "importlib_resources",
    "appdirs",
    "tqdm",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/m-ulmestrand/perfect-cmaps"

[tool.setuptools]
include-package-data = true
packages = ["perfect_cmaps", "perfect_cmaps.lab_control_points", "perfect_cmaps.test_images"]

[tool.setuptools.package-data]
"perfect_cmaps" = ["data/*", "test_images/*", "lab_control_points/*"]
