[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"perfect_cmaps" = ["data/*", "test_images/*", "lab_control_points/*"]
